### ISSUE TITLE
Bug report: asdasd

### ISSUE THREAD

**Issue by maayan-aa** [maayan-aa/issues#18]
### Description
dsfsdfsdf

### How to recreate the bug
1. do this
2. then this
3. then this

### Tasks
- [ ] talk to Zohar
- [ ] work with Guy
- [ ] talk to Gal

### Screenshot
https://ply-widgets-uploads.s3.amazonaws.com/123/2022/3/16/aef95781-8afe-4a75-af23-fabbdf64f7bd.png

### Related to issue(s)
#17 Feature request: Lalala
#16 Bug report: Sample title
#4 Feature request: Table of contents

### Link to Zendesk ticket
https://ply7685.zendesk.com/agent/tickets/4
